const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  saveKey:       (key)  => ipcRenderer.invoke('settings:save-key', key),
  hasKey:        ()     => ipcRenderer.invoke('settings:has-key'),
  clearKey:      ()     => ipcRenderer.invoke('settings:clear-key'),
  getModel:      ()     => ipcRenderer.invoke('settings:get-model'),
  setModel:      (m)    => ipcRenderer.invoke('settings:set-model', m),
  getAuthMode:   ()     => ipcRenderer.invoke('settings:get-auth-mode'),
  setAuthMode:   (mode) => ipcRenderer.invoke('settings:set-auth-mode', mode),
  detectClaudeCLI:   () => ipcRenderer.invoke('auth:detect-claude-cli'),
  openClaudeInstall: () => ipcRenderer.invoke('auth:open-claude-install'),
  openApiKeys:       () => ipcRenderer.invoke('auth:open-api-keys'),
  loadData: ()     => ipcRenderer.invoke('data:load'),
  saveData: (data) => ipcRenderer.invoke('data:save', data),
  run: (payload) => ipcRenderer.invoke('ai:run', payload),
  readClipboardImage: () => ipcRenderer.invoke('clipboard:readImage'),
  exportMarkdown:   (card) => ipcRenderer.invoke('export:card-markdown', card),
  openExportFolder: ()     => ipcRenderer.invoke('export:open-folder'),
  backupJson:       ()     => ipcRenderer.invoke('export:backup-json'),
  openExternal: (url) => ipcRenderer.invoke('app:open-external', url),
  pickDirectory: (defaultPath) => ipcRenderer.invoke('dialog:pickDirectory', defaultPath),
  openTerminal: (cwd) => ipcRenderer.invoke('shell:openTerminal', cwd),
  openEditor: (cwd) => ipcRenderer.invoke('editor:open', cwd),
  showDiff: (payload) => ipcRenderer.invoke('editor:showDiff', payload),
  compactSession: (cardId, sessionId, cwd, useSkills) => ipcRenderer.invoke('claude:compact', cardId, sessionId, cwd, useSkills),
  isCardRunning: (cardId) => ipcRenderer.invoke('claude:isRunning', cardId),
  approvePending: (cardId, pendingId) => ipcRenderer.invoke('claude:approvePending', cardId, pendingId),
  rejectPending: (cardId, pendingId) => ipcRenderer.invoke('claude:rejectPending', cardId, pendingId),
  onPending: (cb) => ipcRenderer.on('claude:pending', (_e, payload) => cb(payload)),
  onPendingResolved: (cb) => ipcRenderer.on('claude:pendingResolved', (_e, payload) => cb(payload)),
  onAiLog: (cb) => ipcRenderer.on('ai:log', (_e, payload) => cb(payload)),
  onAiDone: (cb) => ipcRenderer.on('ai:done', (_e, payload) => cb(payload)),
  onAiSession: (cb) => ipcRenderer.on('ai:session', (_e, payload) => cb(payload)),
});
